java:
  applicationPort: 4650
  image: 'hmctspublic.azurecr.io/ts/translation-service:latest'
  ingressHost: ts-translation-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  aadIdentityName: ts
  keyVaults:
    ts:
      secrets:
        - name: AppInsightsInstrumentationKey
          alias: azure.application-insights.instrumentation-key
        - name: translation-service-POSTGRES-USER
          alias: TS_TRANSLATION_SERVICE_DB_USERNAME
        - name: translation-service-POSTGRES-PASS
          alias: TS_TRANSLATION_SERVICE_DB_PASSWORD
        - name: translation-service-POSTGRES-HOST
          alias: TS_TRANSLATION_SERVICE_DB_HOST
        - name: translation-service-POSTGRES-PORT
          alias: TS_TRANSLATION_SERVICE_DB_PORT
        - name: translation-service-POSTGRES-DATABASE
          alias: TS_TRANSLATION_SERVICE_DB_NAME
        - name: ts-translation-service-s2s-secret
          alias: IDAM_KEY_TS_TRANSLATION_SERVICE

  environment:
    TS_TRANSLATION_SERVICE_DB_OPTIONS: "?stringtype=unspecified&gssEncMode=disable"
    IDAM_OIDC_URL: https://idam-web-public.{{ .Values.global.environment }}.platform.hmcts.net
    OIDC_ISSUER: https://forgerock-am.service.core-compute-idam-{{ .Values.global.environment }}.internal:8443/openam/oauth2/hmcts
    IDAM_API_URL: https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net
    S2S_URL: http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
    TESTING_SUPPORT_ENABLED: false

ccd:
  enabled: false
